import {
  ArrowRight,
  Asterisk,
  CalendarDots,
  Link as LinkIcon,
  Question,
  Quotes,
} from '@phosphor-icons/react'
import { getImageDimensions } from '@sanity/asset-utils'
import React from 'react'
import { Link, useLoaderData } from 'react-router'
import { LogoSymbol } from '#app/components/brand.tsx'
import { SectionHeading } from '#app/components/section-heading.tsx'
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '#app/components/ui/accordion.tsx'
import { Button } from '#app/components/ui/button.js'
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from '#app/components/ui/carousel.tsx'
import { urlFor } from '#app/sanity/instance.ts'
import { loadQuery } from '#app/sanity/loader.server.ts'
import { EventSchema } from '#app/sanity/schema/event.tsx'
import { alphabetMap } from '#app/sanity/schema/year.js'
import { type HomeQueryResult } from '#app/sanity/types.ts'
import { trackEvent } from '#app/utils/analytics.ts'
import { cn } from '#app/utils/misc.js'
import { faqPath, faqs } from '../__faqs.tsx'
import { pillars } from '../ueber-uns+/philosophie+/_layout.tsx'
import { homeQuery } from './query.ts'

export async function loader() {
  const queryResult = await loadQuery<HomeQueryResult>(homeQuery)

  return {
    query: homeQuery,
    data: queryResult.data,
  }
}

export default function Home() {
  const loaderData = useLoaderData<typeof loader>()
  const [latestPost, ...restPosts] = loaderData.data.posts
  const closestEvent = loaderData.data.closestEvent
    ? EventSchema.parse(loaderData.data.closestEvent)
    : null
  const closestOrientation = loaderData.data.closestOrientation
    ? EventSchema.parse(loaderData.data.closestOrientation)
    : null
  const testimonials = loaderData.data.testimonials
  const hero = loaderData.data.hero
  // Type assertion for shoutout until types are properly generated by Sanity
  const shoutout = loaderData.data.shoutout as {
    _id: string
    _type: 'home-shoutout'
    emoji?: string
    title?: string
    subtitle?: string
    buttonText?: string
    buttonLink?: string
  } | null

  return (
    <div className="col-span-1 col-start-1 grid grid-cols-subgrid items-start lg:col-span-4 xl:col-span-2">
      <div className="col-span-full grid grid-cols-12 gap-x-4 gap-y-8 sm:gap-x-6 sm:gap-y-8 md:gap-y-12 lg:gap-x-8 lg:gap-y-16">
        <div
          id="intro-box"
          className={cn(
            'col-span-12 grid grid-cols-1 grid-rows-1 place-self-center',
            '-mx-4 sm:mx-0',
            'relative sm:rounded-md sm:shadow-md',
          )}
        >
          <h1 className="sr-only">Einleitung</h1>
          <figure className="relative col-start-1 col-end-1 row-start-1">
            {hero?.image && (
              <HeroImage image={hero.image} caption={hero.caption} />
            )}
            {hero?.image?.attribution && (
              <figcaption className="bg-foreground/20 absolute right-0 bottom-0 left-0 z-20 px-4 py-1 sm:px-8 md:px-12">
                <p className="text-body-xs text-card/70 text-right">
                  {hero.image.attribution}
                </p>
              </figcaption>
            )}
          </figure>

          <div className="relative col-start-1 row-start-1 flex flex-col items-start justify-between bg-black/10 p-8 sm:rounded-t-md sm:p-16 md:p-20 lg:py-24">
            <LogoSymbol className="text-primary absolute right-12 bottom-12 w-60 opacity-50 sm:right-8 sm:-bottom-24 sm:w-64 md:w-72 md:opacity-60 lg:right-10 lg:w-80" />
            <p className="relative max-w-xl font-sans text-3xl font-bold tracking-tight text-pretty text-white drop-shadow-sm sm:text-4xl md:text-5xl lg:text-6xl">
              Die <strong className="text-secondary font-bold">Walz</strong>{' '}
              soll darauf vor­bereiten, mit Liebe die Welt und die Gesell­schaft
              mitzuge­stalten.
            </p>
            {hero?.caption && <p className="relative">{hero.caption}</p>}
          </div>

          {closestEvent && (
            <article className="bg-muted/60 col-start-1 row-start-2 flex items-center gap-2 p-3 px-4 shadow-inner sm:rounded-b-md sm:px-8 md:px-12">
              <div className="flex flex-col gap-2 md:flex-row md:items-center md:gap-4">
                <div className="flex items-center gap-2">
                  <h1 className="flex items-center gap-1">
                    <CalendarDots
                      size={24}
                      className="text-secondary inline-block"
                    />
                  </h1>
                  <Link
                    key={closestEvent._id}
                    to={`/aktuelles#${closestEvent._id}`}
                    className="font-condensed font-bold"
                  >
                    <span className="">{closestEvent.title}</span> am{' '}
                    <time
                      dateTime={closestEvent.start.date.toISOString()}
                      className=""
                    >
                      {closestEvent.start.date.toLocaleDateString('de-AT', {
                        day: 'numeric',
                        month: 'long',
                      })}
                    </time>
                  </Link>
                </div>{' '}
                <Link
                  to="./aktuelles#schuljahr"
                  className="group/more font-condensed text-muted-foreground flex items-center"
                >
                  <span className="underline-offset-2 group-hover/more:underline">
                    Alle Termine
                  </span>
                  <ArrowRight
                    size={16}
                    className="text-primary transition-transform group-hover/more:translate-x-1"
                  />
                </Link>
              </div>
            </article>
          )}
        </div>
        <section className="col-span-12 grid grid-cols-subgrid gap-y-8">
          <div className="col-span-12 space-y-4 md:col-span-8">
            <div>
              <h1 className="sr-only">Was ist die Walz?</h1>
              <p className="text-body-md xl:text-body-lg max-w-2xl text-pretty">
                In der Walz können Jugendliche zwischen 14 und 19 Jahren in
                einem geschützten Rahmen ihre Potenziale entfalten, ihre
                Möglichkeiten ausloten und werden auf die Matura vorbereitet.
              </p>
            </div>
            <div>
              <p className="text-balance">
                <Link
                  to={'/aktuelles/beitraege/walz-unterschiede'}
                  className="group text-body-md text-muted-foreground"
                >
                  <Question
                    size={28}
                    className="text-primary relative -top-1 inline-flex"
                  />{' '}
                  <span className="underline-offset-2 group-hover:underline">
                    Was unterscheidet die Walz von einer
                    <br className="hidden lg:inline" /> klassischen Oberstufe?
                  </span>
                </Link>
              </p>
            </div>
          </div>

          {shoutout && (
            <div className="col-span-12 md:col-span-4">
              <h1 className="sr-only">Shoutout</h1>
              <div className="border-secondary/30 bg-secondary/20 ring-muted/20 rounded-lg border p-6 ring-8">
                <p className="text-body-md mb-4 text-pretty">
                  {shoutout.emoji && (
                    <span
                      className="relative mb-1"
                      aria-roledescription="emoji"
                    >
                      {shoutout.emoji}
                    </span>
                  )}{' '}
                  {shoutout.title && (
                    <>
                      {shoutout.title}
                      {shoutout.subtitle && (
                        <>
                          <br />
                          <strong className="font-bold">
                            {shoutout.subtitle}
                          </strong>
                        </>
                      )}
                    </>
                  )}
                </p>
                {shoutout.buttonText && shoutout.buttonLink && (
                  <Button
                    asChild
                    size="lg"
                    variant="secondary"
                    className="mr-auto shadow-sm"
                  >
                    <Link
                      to={shoutout.buttonLink}
                      onClick={() => {
                        // The shoutout is editorial, so it only counts as an
                        // admissions CTA when it actually points at the form.
                        if (shoutout.buttonLink?.startsWith('/aufnahme')) {
                          trackEvent('Aufnahme CTA', {
                            position: 'startseite-shoutout',
                          })
                        }
                      }}
                    >
                      {shoutout.buttonText}
                    </Link>
                  </Button>
                )}
              </div>
            </div>
          )}
          {!shoutout && closestOrientation && (
            <div className="col-span-12 md:col-span-4">
              <h1 className="sr-only">Walz kennenlernen</h1>
              <div className="border-secondary/30 bg-secondary/20 ring-muted/20 rounded-lg border p-6 ring-8">
                <p className="text-body-md mb-4 text-pretty">
                  <span className="relative mb-1" aria-roledescription="emoji">
                    👋
                  </span>{' '}
                  Lerne die Walz kennen <br />
                  <strong className="font-bold">
                    {closestOrientation.title}
                    <br />
                    <time
                      dateTime={closestOrientation.start.date.toISOString()}
                      className="font-bold"
                    >
                      {closestOrientation.start.date.toLocaleDateString(
                        'de-AT',
                        {
                          day: 'numeric',
                          month: 'long',
                        },
                      )}
                    </time>
                  </strong>
                </p>
                <Button
                  asChild
                  size="lg"
                  variant="secondary"
                  className="mr-auto shadow-sm"
                >
                  <Link to="/die-walz-kennenlernen">Mehr erfahren</Link>
                </Button>
              </div>
            </div>
          )}
        </section>
        <section className="col-span-12 grid grid-cols-subgrid gap-y-4">
          <header className="col-span-12 flex items-baseline justify-between gap-4">
            <h1 className="text-body-xs text-muted-foreground font-bold tracking-widest uppercase">
              Unser Blog
            </h1>
            <Link
              to="/aktuelles/beitraege/"
              className="group/blog font-condensed text-primary flex items-center gap-1"
            >
              <span className="underline-offset-2 group-hover/blog:underline">
                Alle Beiträge
              </span>
              <ArrowRight
                size={16}
                className="text-primary transition-transform group-hover/blog:translate-x-1"
              />
            </Link>
          </header>
          <div className="col-span-12 grid grid-cols-subgrid gap-y-8">
            <article className="relative col-span-12 grid rounded-lg bg-white shadow-md shadow-gray-200 md:col-span-8 lg:grid-cols-2">
              {latestPost.cover && (
                <Link
                  to={`/aktuelles/beitraege/${latestPost.slug?.current}`}
                  className="group flex lg:row-span-2"
                >
                  <figure className="relative flex opacity-80 grayscale transition-all group-hover:opacity-100 group-hover:grayscale-0">
                    <picture className="flex">
                      <img
                        src={urlFor(latestPost.cover)
                          .quality(70)
                          .width(800)
                          .url()}
                        alt={latestPost.cover.caption}
                        className="aspect-square w-full rounded-t-md object-cover sm:h-auto lg:h-full lg:rounded-tr-none lg:rounded-bl-md"
                      />
                    </picture>
                    {latestPost.cover.attribution && (
                      <figcaption className="bg-foreground/20 absolute right-0 bottom-0 left-0 z-20 px-4 py-1 sm:px-8 md:px-12">
                        <p className="text-body-xs text-card/70 text-right">
                          {latestPost.cover.attribution}
                        </p>
                      </figcaption>
                    )}
                  </figure>
                </Link>
              )}
              <div className="p-6">
                <h1 className="font-condensed text-secondary mb-2 max-w-xs text-xl leading-tight! font-bold text-balance md:text-2xl lg:text-2xl xl:text-3xl">
                  <Link to={`/aktuelles/beitraege/${latestPost.slug?.current}`}>
                    {latestPost.title}
                  </Link>
                </h1>
                <p className="text-body-xs text-muted-foreground">
                  Veröffentlicht am{' '}
                  <time>
                    {new Date(latestPost.publishedAt || 0).toLocaleString(
                      'de-AT',
                      {
                        dateStyle: 'medium',
                      },
                    )}
                  </time>
                </p>
                <p className="text-body-sm lg:text-body-md mt-4 max-w-md leading-snug text-balance">
                  {latestPost.previewText} <span>…</span>
                </p>
              </div>
              <footer className="bg-primary/5 self-end px-6 py-2 lg:col-start-2">
                <Link
                  to={`/aktuelles/beitraege/${latestPost.slug?.current}`}
                  className="group/more font-condensed text-primary flex items-center text-lg"
                >
                  <span className="underline-offset-2 group-hover/more:underline">
                    Weiterlesen
                  </span>
                  <ArrowRight
                    size={20}
                    className="text-primary ml-auto transition-transform group-hover/more:translate-x-1"
                  />
                </Link>
              </footer>
            </article>
            <div className="col-span-12 grid auto-rows-min gap-y-8 md:col-span-4">
              {restPosts.map((post, idx) => {
                return (
                  <React.Fragment key={idx}>
                    <article key={idx} className="relative max-w-prose">
                      <h1 className="font-condensed max-w-xs leading-tight! font-bold text-balance md:text-lg">
                        <Link to={`/aktuelles/beitraege/${post.slug?.current}`}>
                          {post.title}
                        </Link>
                      </h1>
                      <p className="text-body-sm text-muted-foreground mt-2 max-w-md leading-snug text-balance">
                        {post.previewText?.replace(/^(.{90}[^\s]*).*/, '$1')}{' '}
                        <span>…</span>
                      </p>
                      <footer className="mt-2">
                        <Link
                          to={`/aktuelles/beitraege/${post.slug?.current}`}
                          className="font-condensed text-primary"
                        >
                          <span className="underline-offset-2 group-hover/more:underline">
                            Weiterlesen
                          </span>
                        </Link>
                      </footer>
                    </article>
                    {idx < restPosts.length - 1 && <hr className="" />}
                  </React.Fragment>
                )
              })}
            </div>
          </div>
        </section>
        <section className="col-span-12 grid grid-cols-subgrid gap-y-8">
          <header className="col-span-12 py-4 md:py-8 lg:py-12">
            <SectionHeading id="philosophie">Unsere Philosophie</SectionHeading>
          </header>

          <div className="col-span-12 grid grid-cols-subgrid gap-y-8">
            {pillars.map((entry, idx) => {
              return (
                <div
                  key={idx}
                  className="col-span-12 md:col-span-6 lg:col-span-4"
                >
                  <LinkPhotoCard
                    title={entry.title}
                    abstract={entry.abstract}
                    image={entry.image}
                    link={entry.link}
                  />
                </div>
              )
            })}
          </div>
        </section>
        <section className="col-span-12 space-y-8">
          <header className="py-4 md:py-8">
            <SectionHeading id="testimonials">
              Stimmen aus der Walz
            </SectionHeading>
          </header>
          <Carousel
            className="bg-muted/30 -mx-4 space-y-8 overflow-hidden py-8 shadow-inner sm:mx-0 sm:rounded-md"
            opts={{ loop: true }}
          >
            <CarouselContent className="-ml-4 px-4 py-2 sm:-ml-8 sm:px-8 lg:-ml-20">
              {testimonials.map((testimonial, idx) => {
                return (
                  <CarouselItem
                    key={idx}
                    className="flex items-start justify-center pl-4 sm:pl-8 md:items-center lg:pl-20"
                  >
                    <TestimonialCard idx={idx} {...testimonial} />
                  </CarouselItem>
                )
              })}
            </CarouselContent>
            <div className="flex justify-center gap-4 px-8">
              <CarouselPrevious className="self-end" />
              <CarouselNext className="self-start" />
            </div>
          </Carousel>
        </section>
        <FaqSection nextOrientation={closestOrientation} />
        <section className="col-span-12 grid grid-cols-subgrid gap-y-8">
          <header className="col-span-12 py-4 md:py-8">
            <SectionHeading id="kontakt">Anfahrt & Kontakt</SectionHeading>
          </header>
          <div className="col-span-12 grid grid-cols-subgrid gap-y-8">
            <Link
              to="https://goo.gl/maps/sb3LQfsePwU3zMPg8"
              className="bg-muted/10 relative col-span-12 h-72 overflow-hidden rounded md:col-span-8 lg:h-96"
            >
              <img
                src={`https://maps.googleapis.com/maps/api/staticmap?center=48.1984402,16.2922301&zoom=16&size=800x500&key=${ENV.GOOGLE_MAPS_API_KEY}&scale=2&map_id=8811b5d90ece1ea5`}
                alt="Karte"
                className="h-full w-full object-cover"
              />
              <div className="shadow-muted/80 absolute top-0 left-0 h-full w-full overflow-hidden border shadow-inner"></div>
            </Link>
            <div className="col-span-12 md:col-span-4">
              <h2 className="text-body-xs text-muted-foreground mb-4 font-bold tracking-widest uppercase">
                Kontakt
              </h2>
              <div className="lg:text-body-md">
                <p>
                  <strong className="text-primary">
                    Walz Wiener Lernzentrum
                  </strong>
                </p>
                <p>Heinrich-Collin-Straße 9</p>
                <p>1140 Wien</p>
                <p>Tel.: 01 8042939</p>
                <p>Fax: 01 8042939-2000</p>
                <p>Email: office@walz.at</p>
              </div>
              <div className="mt-4">
                <p className="text-balance">
                  <Link
                    to="/rundgang"
                    className="text-muted-foreground underline-offset-2 hover:underline"
                  >
                    Klicke hier um die Walz bei einem virtuellen Rundgang
                    kennenzulernen.{' '}
                    <LinkIcon
                      className="text-primary relative top-px inline align-baseline"
                      size={16}
                    />
                  </Link>
                </p>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  )
}

type TestimonialCardProps = HomeQueryResult['testimonials'][0] & { idx: number }

function TestimonialCard({ idx, ...entry }: TestimonialCardProps) {
  return (
    <blockquote
      key={idx}
      className="bg-card relative grid min-h-72 max-w-3xl grid-cols-1 items-start overflow-hidden rounded-lg shadow-md md:grid-cols-12"
    >
      <div className="bg-card relative h-full p-6 md:col-span-7 md:col-start-1 md:p-8">
        <p className="text-muted-foreground md:text-body-md text-balance md:min-h-32">
          {entry.quote}
          <Quotes
            role="presentation"
            weight="fill"
            className="text-secondary float-right h-12 w-12 md:h-16 md:w-16"
          />
        </p>
      </div>
      <footer className="bg-secondary/10 flex h-full flex-col justify-between gap-4 p-6 md:col-span-5 md:col-start-8 md:p-8">
        <figure
          className="relative flex w-24 items-center justify-center rounded-full lg:w-36"
          aria-hidden="true"
        >
          <img
            src={urlFor(entry.photo?.asset ?? {})
              .quality(70)
              .format('webp')
              .width(200)
              .height(200)
              .url()}
            alt={entry.photo?.alt || ''}
            className="rounded-full shadow-md"
          />
          <div
            role="presentation"
            className="ring-foreground/10 absolute inset-0 rounded-full ring-2 ring-inset"
          />
        </figure>
        <div className="">
          <p className="text-primary md:text-body-md font-bold">
            {entry.name}
            {'  '}
            <span className="font-greek text-secondary align-super font-bold">
              {alphabetMap[entry.year?.letter ?? '']}
            </span>{' '}
          </p>
          <p className="mb-2 leading-none">
            <span className="text-body-2xs text-muted-foreground tracking-widest uppercase">
              Maturajahr{' '}
              <span>
                {entry.year?.graduatedAt &&
                  new Date(entry.year.graduatedAt).getFullYear()}
              </span>
            </span>
          </p>
          <p>{entry.achievement}</p>
        </div>
      </footer>
    </blockquote>
  )
}

type FaqSectionProps = {
  /** The next event for getting to know the school, when one is scheduled. */
  nextOrientation?: {
    title: string
    start: { date: Date; time?: string }
  } | null
}

/**
 * Teasers for the frequently asked questions, with the first answer open so
 * the section shows an answer rather than just a list of links. Full answers
 * live on /haeufige-fragen.
 */
export function FaqSection({ nextOrientation = null }: FaqSectionProps) {
  return (
    <section className="col-span-12 space-y-8">
      <header className="py-4 md:py-8">
        <SectionHeading id="faq">Häufige Fragen</SectionHeading>
      </header>
      <Accordion
        type="single"
        collapsible
        defaultValue={faqs[0]?.slug}
        onValueChange={value => {
          // Empty when an item is collapsed — only opens are interesting.
          if (value) trackEvent('FAQ Open', { faq: value })
        }}
        className="bg-card -mx-4 overflow-hidden shadow-sm sm:mx-0 sm:rounded-md"
      >
        {faqs.map(faq => (
          <AccordionItem
            key={faq.slug}
            value={faq.slug}
            className="border-primary/10 last:border-b-0"
          >
            <AccordionTrigger className="font-condensed text-primary text-body-md md:text-body-lg gap-4 px-4 text-left font-bold underline-offset-2 sm:px-6">
              <span className="flex items-start gap-2">
                <Asterisk
                  aria-hidden
                  className="text-secondary relative top-1 flex-none md:top-[6px]"
                />
                {faq.question}
              </span>
            </AccordionTrigger>
            <AccordionContent className="px-4 pl-10 text-base sm:px-6 sm:pl-12 md:text-lg">
              <p className="max-w-prose">{faq.teaser}</p>
              <Link
                to={faqPath(faq)}
                onClick={() => trackEvent('FAQ Read More', { faq: faq.slug })}
                className="group/more font-condensed text-muted-foreground mt-3 flex items-center gap-1 text-lg"
              >
                <span className="underline-offset-2 group-hover/more:underline">
                  Ganze Antwort lesen
                </span>
                <ArrowRight
                  size={16}
                  className="text-primary transition-transform group-hover/more:translate-x-1"
                />
              </Link>
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div className="space-y-3">
          <p className="text-body-md max-w-prose text-pretty">
            Frage nicht dabei? Schreib uns – wir antworten dir persönlich.
            {nextOrientation ? (
              <>
                {' '}
                Oder lerne uns beim{' '}
                <strong className="font-bold">
                  {nextOrientation.title}
                </strong>{' '}
                am{' '}
                <time dateTime={nextOrientation.start.date.toISOString()}>
                  {nextOrientation.start.date.toLocaleDateString('de-AT', {
                    day: 'numeric',
                    month: 'long',
                  })}
                </time>
                {nextOrientation.start.time
                  ? ` um ${nextOrientation.start.time} Uhr`
                  : ''}{' '}
                kennen.
              </>
            ) : null}
          </p>
          <div className="flex flex-wrap items-center gap-4">
            <Button asChild variant="outline">
              <Link to="/kontakt">Frage stellen</Link>
            </Button>
            {nextOrientation ? (
              <Link
                to="/die-walz-kennenlernen"
                className="group/termine font-condensed text-primary flex items-center gap-1"
              >
                <span className="underline-offset-2 group-hover/termine:underline">
                  Termine ansehen
                </span>
                <ArrowRight
                  size={16}
                  className="text-primary transition-transform group-hover/termine:translate-x-1"
                />
              </Link>
            ) : null}
          </div>
        </div>
        <Link
          to="/haeufige-fragen"
          className="group/faqs font-condensed text-primary flex items-center gap-1"
        >
          <span className="underline-offset-2 group-hover/faqs:underline">
            Alle Fragen
          </span>
          <ArrowRight
            size={16}
            className="text-primary transition-transform group-hover/faqs:translate-x-1"
          />
        </Link>
      </div>
    </section>
  )
}

function HeroImage({ image, caption }: { image: any; caption: string | null }) {
  const { width, height } = getImageDimensions(image)
  return (
    <picture className="flex">
      <source
        srcSet={urlFor(image).quality(70).width(800).url()}
        media="(max-width: 800px)"
      />
      <img
        src={urlFor(image).quality(70).width(1800).url()}
        width={width}
        height={height}
        alt={caption || ''}
        className="aspect-square w-full object-cover sm:aspect-auto sm:h-auto sm:rounded-t-md md:aspect-21/12"
      />
    </picture>
  )
}

export function LinkPhotoCard({
  title,
  abstract,
  image,
  imageAlt,
  link,
}: {
  title: string
  abstract: string
  image: string
  imageAlt?: string
  link: string
}) {
  return (
    <Link
      to={link}
      prefetch="render"
      className="group focus:outline-primary flex flex-col rounded-lg"
    >
      <div className="relative">
        <div className="shadow-muted/50 relative translate-y-4 overflow-hidden rounded-lg shadow-xl transition-all group-hover:translate-y-2">
          <img
            src={image}
            alt={imageAlt}
            className="ascpet-square bg-muted h-48 w-full object-cover grayscale group-hover:grayscale-0"
          />
          <div
            role="presentation"
            className="ring-foreground/20 absolute inset-0 rounded-lg ring-1 ring-inset"
          />
        </div>
      </div>

      <div className="border-t-primary bg-card relative rounded-b-lg border-t-4 p-6 pt-6 shadow-md">
        <hgroup className="flex-1">
          <h1 className="font-condensed text-h4 text-secondary md:text-h3 mb-1 font-bold">
            {title}
          </h1>
          <p className="text-lg leading-none font-bold">{abstract}</p>
        </hgroup>
        <div className="group/more font-condensed text-muted-foreground mt-4 flex items-center gap-1 text-lg">
          <span className="underline-offset-2 group-hover/more:underline">
            Mehr erfahren
          </span>
          <ArrowRight
            size={20}
            className="text-primary transition-transform group-hover/more:translate-x-1"
          />
        </div>
      </div>
    </Link>
  )
}
