# fly.toml app configuration file generated for walz on 2023-06-07T09:42:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "walz"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  allowed_public_ports = [ ]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [services.concurrency]
    hard_limit = 100
    soft_limit = 80
    type = "requests"

  [[services.ports]]
    handlers = [ "http" ]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = [ "tls", "http" ]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/resources/healthcheck"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false
    headers = { }
