name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependabot-auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Wait for CI to complete
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-ci
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "🚀 Deploy"
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 1800 # 30 minutes
          
      - name: Auto-merge patch and minor updates
        if: |
          steps.wait-for-ci.outputs.conclusion == 'success' && (
            steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
            (steps.metadata.outputs.update-type == 'version-update:semver-minor' && 
             !contains(steps.metadata.outputs.dependency-names, 'react-router') &&
             !contains(steps.metadata.outputs.dependency-names, '@react-router'))
          )
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}