name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    name: 🎭 Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: test
    env:
      SENTRY_DSN: https://20c628330a59c4df20fd2c0ba7f2873c@o4505819035467776.ingest.sentry.io/4505819065286656
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      BUTTONDOWN_API_KEY: ${{ secrets.BUTTONDOWN_API_KEY }}
      HONEYPOT_SECRET: ${{ secrets.HONEYPOT_SECRET }}
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      SANITY_PUBLIC_PROJECT_ID: iaejvb99
      SANITY_PUBLIC_DATASET: production
      SANITY_PUBLIC_API_VERSION: 2023-10-01
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
